version: "3.7"

services:
  web:
    image: nginx
    volumes:
    - .conf:/etc/nginx/conf.d/default.conf

    ports:
      - 8080:8080
    networks:
      - swarm_network

networks:
  swarm_network:
    external: true