version: "3.7"

services:
  traefik:
    image: traefik:2.3
    ports:
      # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
      - "80:80"
      # Listen on port 443, default for HTTPS
      - "443:443"
      - "8080:8080"
    networks: 
      - swarm_network
    configs:
      - source: traefik_static
        target: /etc/traefik/traefik.yml

configs:
  traefik_static:
    file: ./traefik.yml

networks:
  swarm_network:
    external: true