################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: true

################################################################
# EntryPoints configuration
################################################################

entryPoints:
  web:
    address: :80

  websecure:
    address: :443

################################################################
# Traefik logs configuration
################################################################

log:
  level: DEBUG # DEBUG, INFO, WARNING, ERROR, CRITICAL
  filePath: os.Stdout
  format: common  # common, json, logfmt

################################################################
# Access logs configuration
################################################################

accessLog:
  filePath: os.Stdout
  format: common # common, json

################################################################
# API and dashboard configuration
################################################################

api:
  insecure: true
  dashboard: true

################################################################
# Ping configuration
################################################################

# Enable ping
#ping:
  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
#  entryPoint: traefik

################################################################
# Docker configuration backend
################################################################

providers:
  docker:
    # endpoint: "tcp://127.0.0.1:2377"
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: true
    useBindPortIP: false
    network: swarm_network
    watch: true


tracing:
  elastic: {}